# Site settings
title: "Elena Stella"
author: "Elena Stella"
email: "elena.stella@kellogg.northwestern.edu "
description: "Economist working on corporate finance and applied microeconomics."

# GitHub Pages settings with custom domain
baseurl: "" # Leave empty for custom domain
#url: "https://elena-stella.com" # Your custom domain
url: "https://elenastella.github.io" # Your custom domain


# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty

# GitHub Pages safe plugins only
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Kramdown settings
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Include and exclude
include:
  - _pages
  - assets

exclude:
  - vendor
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - node_modules
  - "*.gem"
  - "*.gemspec"

# SEO settings
lang: en_US

# Academic settings
scholar:
  style: apa
  locale: en
